# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubectx < Formula
  desc "Command line tool for managing Kubernetes contexts"
  homepage "https://github.com/philipparndt/kubectx"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/philipparndt/kubectx/releases/download/v0.1.0/kubectx_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "123"

      def install
        bin.install "kubectx"
      end
    end
    on_arm do
      url "https://github.com/philipparndt/kubectx/releases/download/v0.1.0/kubectx_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "123"

      def install
        bin.install "kubectx"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/philipparndt/kubectx/releases/download/v0.1.0/kubectx_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "123"

        def install
          bin.install "kubectx"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/philipparndt/kubectx/releases/download/v0.1.0/kubectx_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "123"

        def install
          bin.install "kubectx"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run using kubectx
    EOS
  end
end
